### ISSUE TITLE
Inception treained model

### ISSUE THREAD

**Issue by Ellyuca** [nesl/adversarial_genattack#7]
Hi,
I am interesting in using the genattack method for some benchmark experiments. Unfortunately, I am having trouble downloading the inception-v3 model.

Could you provide the pretrained model used in this repo?

Thank you very much.

**Comment by malzantot** [comment]
I think the server that had the pre-trained model could be down.  Would you mind trying this instead http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz
[I haven't tried this myself] but should work as it is a checkpoint of the same pre-trained model version we used. (Inception-v3). Source for the link: https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models

**Comment by Ellyuca** [comment]
Thanks. 
I am going to give it a try right now!
I'll get back to you with some feedback.

Thanks a lot for the quick reply!

**Comment by Ellyuca** [comment]
I am getting this error now and I can't figure it out.
Do you have any idea how to fix it?

"""
Traceback (most recent call last):
  File "setup_inception.py", line 329, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "setup_inception.py", line 284, in main
    model = InceptionModelPrediction(sess, True)
  File "setup_inception.py", line 196, in __init__
    return_elements=[output_name])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Requested return tensor '/InceptionV3/Predictions/Softmax:0' not found in graph def
"""
